FROM golang:1.23.0 as builder

WORKDIR /app

COPY go.mod ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o app .


FROM alpine

RUN apk add --no-cache wget

WORKDIR /root


COPY --from=builder /app/app .

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD wget --spider http://localhost:8080/health || exit 1


CMD [ "./app" ]

