package utils

import "fmt"

func CreateContentRefresh() string {
	return `# SERVER CONFIGURATION
APP_PORT=8080
APP_HOST=localhost
METRICT_PORT=8088

# DATABASE CONFIGURATION
DB_DRIVER=your_driver
DB_USER=your_user
DB_HOST=localhost
DB_PORT=3306
DB_NAME=your_database
DB_PASSWORD=your_password

# REDIS CONFIGURATION
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=

# TOKEN EXPIRATION
ACCESS_TOKEN_TTL=900
REFRESH_TOKEN_TTL=604800

# SESSION SETTINGS
SESSION_TTL=604800
IDLE_TIMEOUT=1800

# BLACKLIST SETTINGS
REVOKED_TTL=300

# RATE LIMIT
RATE_LIMIT_PERIOD=60
RATE_LIMIT_MAX=100 
`
}

func CreateContentRefreshUsed(
	APP_PORT string,
	METRICT_PORT string,
	APP_HOST string,
	DB_DRIVER string,
	DB_USER string,
	DB_HOST string,
	DB_PORT string,
	DB_NAME string,
	DB_PASSWORD string,
	DB_URL string,
	REDIS_HOST string,
	REDIS_PORT string,
	REDIS_PASSWORD string,
	ACCESS_TOKEN_TTL string,
	REFRESH_TOKEN_TTL string,
	SESSION_TTL string,
	IDLE_TIMEOUT string,
	REVOKED_TTL string,
	RATE_LIMIT_PERIOD string,
	RATE_LIMIT_MAX string,
) string {
	return fmt.Sprintf(`# SERVER CONFIGURATION
APP_PORT=%s
APP_HOST=%s
METRICT_PORT=%s

# DATABASE CONFIGURATION
DB_DRIVER=%s
DB_USER=%s
DB_HOST=%s
DB_PORT=%s
DB_NAME=%s
DB_PASSWORD=%s
DB_URL=%s

# REDIS CONFIGURATION
REDIS_HOST=%s
REDIS_PORT=%s
REDIS_PASSWORD=%s

# TOKEN EXPIRATION
ACCESS_TOKEN_TTL=%s
REFRESH_TOKEN_TTL=%s

# SESSION SETTINGS
SESSION_TTL=%s
IDLE_TIMEOUT=%s

# BLACKLIST SETTINGS
REVOKED_TTL=%s

# RATE LIMIT
RATE_LIMIT_PERIOD=%s
RATE_LIMIT_MAX=%s
`, APP_PORT, APP_HOST, METRICT_PORT,
		DB_DRIVER, DB_USER, DB_HOST, DB_PORT, DB_NAME, DB_PASSWORD, DB_URL,
		REDIS_HOST, REDIS_PORT, REDIS_PASSWORD,
		ACCESS_TOKEN_TTL, REFRESH_TOKEN_TTL,
		SESSION_TTL, IDLE_TIMEOUT,
		REVOKED_TTL,
		RATE_LIMIT_PERIOD,
		RATE_LIMIT_MAX,
	)
}
