package utils

import ()

func CreateContent() string {
	return `# SERVER CONFIGURATION
APP_PORT=8080
APP_HOST=localhost
APP_ENV=development
METRIC_PORT=8088
UID_BITS=26
REQUEST_KEY=request_context

# LOGGING
LOG_PATH=./logs

# CORS 
CORS_ALLOW_ORIGINS=*
CORS_ALLOW_METHODS=GET,POST,PUT,DELETE,OPTIONS
CORS_ALLOW_HEADERS=Content-Type,Authorization

# TIMEZONE 
TIMEZONE=UTC
SUPPORTED_LANGUAGES=en-US,vi-VN

# DATABASE CONFIGURATION
DB_DRIVER=your_driver
DB_USER=your_user
DB_HOST=localhost
DB_PORT=3306
DB_NAME=your_database
DB_PASSWORD=your_password

# Database Connection Pool
DB_MAX_OPEN_CONNS=100
DB_MAX_IDLE_CONNS=10
DB_CONN_MAX_LIFETIME=60
DB_CONN_MAX_IDLE_TIME=600
SLOW_THRESHOLD=5

# REDIS CONFIGURATION
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASSWORD=

# RATE LIMIT
RATE_LIMIT_PERIOD=60
RATE_LIMIT_MAX=100 
`
}
