baseURL = "https://DVV-15324.github.io/witches/"

title = "Witches Documentation"
theme = "hugo-book"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    label = "English"
    contentDir = "content/docs/en"
    weight = 1

  [languages.vi]
    label = "Tiếng Việt"
    contentDir = "content/docs/vi"
    weight = 2

[params]
  BookSection = "/"
  BookTheme = "auto"
  BookToC = true
  BookSearch = true
  BookComments = false
  BookPortableLinks = true
  BookServiceWorker = false
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']