basePath: /api/v1
definitions:
  main.ModelUser:
    properties:
      age:
        example: 22
        maximum: 100
        minimum: 0
        type: integer
      name:
        example: Dinh Viet Vu
        maxLength: 10
        minLength: 0
        type: string
    required:
    - age
    - name
    type: object
host: localhost:8080
info:
  contact: {}
  description: API cua Dinh Viet Vu
  title: API Dinh Viet Vu
  version: "1.0"
paths:
  /user:
    get:
      consumes:
      - application/json
      description: Hiển thị tất cả User
      parameters:
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.ModelUser'
            type: array
        "400":
          description: Loi
          schema:
            type: string
      summary: Hiển thị hết User
      tags:
      - user
    post:
      consumes:
      - application/json
      description: Tạo mới User
      parameters:
      - description: User Data
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.ModelUser'
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.ModelUser'
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Tạo User
      tags:
      - user
  /user/{name}:
    delete:
      consumes:
      - application/json
      description: Xóa User theo Name
      parameters:
      - description: User Name
        in: path
        name: name
        required: true
        type: string
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Delete Success
          schema:
            type: string
        "404":
          description: User Not Found
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Xóa User bởi Name
      tags:
      - user
    get:
      consumes:
      - application/json
      description: Hiển thị User bởi name
      parameters:
      - description: User Name
        in: path
        name: name
        required: true
        type: string
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ModelUser'
        "400":
          description: Loi
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Hiển thị User bởi Name
      tags:
      - user
    put:
      consumes:
      - application/json
      description: Cập nhật User theo Name
      parameters:
      - description: User Name
        in: path
        name: name
        required: true
        type: string
      - description: Updated User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.ModelUser'
      - description: Bearer Token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.ModelUser'
        "400":
          description: Loi
          schema:
            type: string
        "404":
          description: User Not Found
          schema:
            type: string
      security:
      - BearerAuth: []
      summary: Cập nhật User bởi Name
      tags:
      - user
swagger: "2.0"
